version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  orders-products-api:
    depends_on:
      - db
    build: .
    container_name: 'orders-products-api'
    restart: always
    ports:
      - '3005:3005'
    networks:
      - webnet
    environment:
      - MYSQL_SERVER=localhost
      - MYSQL_PORT=3306
      - MYSQL_DB=shop
      - MYSQL_USER=root
      - MYSQL_PW=S3cret
      - APP_PORT=3005
networks:
  webnet:

volumes:
  db:
    driver: local
